project:
  type: book
  output-dir: _site
  render:
    - "*.qmd"
    - "!_drafts/"

profile:
  group:
    - [web, print]

book:
  title: "Computational Game Theory"
  subtitle: "Course information and materials"
  author: "Tomáš Kroupa"
  output-file: "computational-game-theory"
  search: true
  page-navigation: true
  sidebar:
    tools:
      - icon: file-earmark-pdf
        text: "Download textbook (PDF)"
        href: downloads/computational-game-theory.pdf

  appendices:
    - games/normal-form-game-catalogue.qmd
    - references.qmd

bibliography: references.bib
lang: en

execute:
  freeze: auto
